services:
  db:
    extends:
      file: docker-compose.base.yml
      service: db
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: admin

  kafka:
    extends:
      file: docker-compose.base.yml
      service: kafka

  kafka_ui:
    extends:
      file: docker-compose.base.yml
      service: kafka_ui
    depends_on:
      kafka:
        condition: service_healthy

  db_nosql:
    extends:
      file: docker-compose.base.yml
      service: db_nosql
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin

  user_service:
    build:
      context: ../booking-app-user-service
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      mynet:
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - SERVICE_NAME=user_service
      - OTEL_COLLECTOR=http://otel-collector:4317
      - LOKI=http://loki:3100
      - ConnectionStrings__DefaultConnection=Server=db;Port=3306;Database=booking-user-service;Uid=root;Pwd=admin;


  accommodation_service:
    build:
      context: ../booking-app-accommodation-service
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - mynet
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - SERVICE_NAME=accommodation_service
      - OTEL_COLLECTOR=http://otel-collector:4317
      - LOKI=http://loki:3100
      - ConnectionStrings__DefaultConnection=Server=db;Port=3306;Database=booking-accommodation-service;Uid=root;Pwd=admin;

  booking_service:
    build:
      context: ../booking-app-booking-service
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - mynet
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - SERVICE_NAME=booking_service
      - OTEL_COLLECTOR=http://otel-collector:4317
      - LOKI=http://loki:3100
      - ConnectionStrings__DefaultConnection=Server=db;Port=3306;Database=booking-booking-service;Uid=root;Pwd=admin;

  notification_service:
    build:
      context: ../booking-app-notification-service
      dockerfile: Dockerfile
    depends_on:
      db_nosql:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - mynet
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - SERVICE_NAME=notification_service
      - OTEL_COLLECTOR=http://otel-collector:4317
      - LOKI=http://loki:3100
      - ConnectionStrings__DefaultConnection=mongodb://root:admin@db_nosql:27017/booking-notification-service

  booking_front:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - mynet
    depends_on:
      - booking_service
      - accommodation_service
      - user_service
      - notification_service

volumes:
  db-data:
  mongo_data:
  kafka_data:

networks:
  mynet:
    driver: bridge
    name: mynet
