{
 "title": "ASP.NET Core Metrics",
 "tags": [
  "dotnet",
  "prometheus",
  "aspnetcore"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": "label_values(http_server_active_requests,job)"
   },
   {
    "name": "instance",
    "query": "label_values(http_server_active_requests{job=~\"$job\"},instance)"
   },
   {
    "name": "service",
    "query": "label_values(http_server_active_requests,exported_job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceil(increase(http_server_request_duration_seconds_count{exported_job=~\"$service\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "2xx + 3xx Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceil(increase(http_server_request_duration_seconds_count{job=~\"$job\", instance=~\"$instance\", exported_job=~\"$service\", http_response_status_code=~\"[23]..\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "4xx + 5xx Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  increase(\r\n    http_server_request_duration_seconds_count{exported_job=\"$service\", http_response_status_code=~\"4..|5..\"}[$__range]\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Traffic (GB)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_response_size_bytes_total{service_name=\"$service\"}[$__range]))  / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "404 Requests by Route",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (http_route, http_request_method) (\r\n  ceil(\r\n    increase(\r\n      http_server_request_duration_seconds_count{\r\n        exported_job=\"$service\",\r\n        http_response_status_code=\"404\",\r\n        http_route!=\"\"\r\n      }[$__range]\r\n    )\r\n  )\r\n)\r\n"
    }
   ]
  },
  {
   "title": "Unique Visitors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(unique_visitors_total{exported_job=\"$service\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}