{
 "title": "Windows Exporter Core Metrics",
 "description": "Windows Exporter dashboard for CPU, Memory, Disk, Network, OS, Service, System (Adjusted)",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "Server",
    "query": "label_values(windows_cpu_time_total, instance)"
   },
   { "name": "interval", "label": "Rate Interval", "query": "5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(windows_cpu_time_total{mode='idle', instance=~\"$server\"}[$interval])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Physical Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "windows_memory_physical_bytes{instance=~\"$server\"} - windows_memory_available_bytes{instance=~\"$server\"}",
     "legendFormat": "Used Memory"
    },
    {
     "expr": "windows_memory_available_bytes{instance=~\"$server\"}",
     "legendFormat": "Available Memory"
    }
   ]
  },
  {
   "title": "Logical Disk Used (%)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\r\n  windows_logical_disk_size_bytes{instance=~\"$server\", volume=\"C:\"} \r\n  - windows_logical_disk_free_bytes{instance=~\"$server\", volume=\"C:\"}\r\n) / windows_logical_disk_size_bytes{instance=~\"$server\", volume=\"C:\"} * 100\r\n",
     "legendFormat": "{{volume}} Used (%)"
    }
   ]
  },
  {
   "title": "Network Traffic (Bps)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes/sec" } },
   "targets": [
    {
     "expr": "irate(windows_net_bytes_received_total{instance=~\"$server\"}[$interval])",
     "legendFormat": "{{instance}} Receive (Bps)"
    },
    {
     "expr": "irate(windows_net_bytes_sent_total{instance=~\"$server\"}[$interval])",
     "legendFormat": "{{instance}} Transmit (Bps)"
    }
   ]
  }
 ]
}